// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nfcayrabdjpclfqzoxpt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5mY2F5cmFiZGpwY2xmcXpveHB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1MDkwMjIsImV4cCI6MjA3NDA4NTAyMn0.BNbclEfFlZo6b1iLd-DJkthxAISSgijMMl0aBCor-ac";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});